language: node_js
node_js:
  - 16

services:
  - docker

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed namha1/udagram-api-feed
  - docker tag udagram-api-user namha1/udagram-api-user
  - docker tag udagram-frontend namha1/udagram-frontend:v6
  - docker tag udagram-reverseproxy namha1/udagram-reverseproxy


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml push
  - docker push namha1/udagram-api-feed
  - docker push namha1/udagram-api-user
  - docker push namha1/udagram-reverseproxy
  - docker push namha1/udagram-frontend:v6